//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akter_and_Spectacle
    {
        public int id_spec { get; set; }
        public int id_akter { get; set; }
        public string Role { get; set; }
    
        public virtual Akter Akter { get; set; }
        public virtual Spectacle Spectacle { get; set; }
    }
}
