//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spectacle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spectacle()
        {
            this.Akter_and_Spectacle = new HashSet<Akter_and_Spectacle>();
        }
    
        public int id_spectacle { get; set; }
        public int id_post { get; set; }
        public int id_scen { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Nazvanie { get; set; }
        public int id_xydoz { get; set; }
        public int id_zanr { get; set; }
        public byte[] Poster { get; set; }
        public Nullable<int> Ostatok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akter_and_Spectacle> Akter_and_Spectacle { get; set; }
        public virtual Pointer Pointer { get; set; }
        public virtual Postanovshik Postanovshik { get; set; }
        public virtual Screenwriter Screenwriter { get; set; }
        public virtual Zanr Zanr { get; set; }
    }
}
